# H1 TTILE
## H2 TITLE

In [84]:
print("Buy the dip ?")

Buy the dip ?


In [85]:
import numpy as np

myArray = np.array([1, 01.2021, "Hello World", {"key": "value"}, [0,1,2,3,4], (5,6), {7,8}, True], dtype=object)

for i in myArray:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [86]:
my1dArray = np.zeros(300)


my2dArray = my1dArray.reshape(3, 100) 


for i in my2dArray:
    print(i)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [87]:
array = np.arange(1, 101) # 101 is exclude

print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [88]:
oddMask = array % 2 == 1 

myOddArray = array[oddMask]

print(myOddArray)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [89]:
reversedArray = np.flip(array)

print(reversedArray)


evenMask = reversedArray % 2 == 0

myEvenArray = reversedArray[evenMask]

print(myEvenArray)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [90]:
modifiedArray = array.copy()

modifiedArray[1::3] = 0

print(modifiedArray)

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


In [91]:
myData1 = np.arange(1, 51)
myData2 = np.arange(51, 101)
myConcatenateData = np.concatenate((myData1, myData2))
myReshapedData = myConcatenateData.reshape((10, 10))
print("myData1 :\n", myData1, "\n myData2 :\n", myData2, "\n myConcatenateData :\n", myConcatenateData, "\n myReshapedData :\n", myReshapedData)

myData1 :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 
 myData2 :
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100] 
 myConcatenateData :
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 
 myReshapedData :
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  

In [92]:
int8Array = np.ones((9, 9), dtype=np.int8)

modifiedArrayForSlicing = np.copy(int8Array)
modifiedArrayForBroadcasting = np.copy(int8Array)

modifiedArrayForSlicing[1:8, 1:8] = 0
modifiedArrayForSlicing[2:7:4, 2:7] = 1
modifiedArrayForSlicing[2:7, 2:7:4] = 1
modifiedArrayForSlicing[4:5, 4:5] = 1



array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)

broadcastingResult = array_1[:, None] + array_2


print("int8Array :\n",int8Array, "\n modifiedArray :\n", modifiedArrayForSlicing, "\n broadcastingResult :\n", broadcastingResult)


int8Array :
 [[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 
 modifiedArray :
 [[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 
 broadcastingResult :
 [[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


In [93]:
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan


thirdColumn = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

newGrades = np.column_stack((grades, thirdColumn))
print("grades :\n", grades, "\n thirdColumn :\n", thirdColumn, "\n new grades \n", newGrades)


grades :
 [[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]] 
 thirdColumn :
 [7. 2. 8. 9. 8. 2. 8. 6. 9. 8.] 
 new grades 
 [[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [94]:
data = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1, dtype=np.float32)

arraySizeInBytes = data.nbytes


secondRow = data[1:2, :]
seventhRow = data[6:7, :]
twelfthRow = data[11:12, :]

alcoholPercentageCheck = np.isnan(data[:, 10])
alcoholPercentage = np.any(data[:, 10] > 20)

alcoholAverageCheck = np.isnan(data[:, 10])
alcoholSomme = np.sum(data[:, 10])
alcoholLen = len(data[:, 10])
alcoholAverage = alcoholSomme / alcoholLen


print(
    "arraySizeInBytes :\n", arraySizeInBytes,
    "\n secondRow :\n", secondRow,
    "\n seventhRow :\n", seventhRow,
    "\n twelfthRow :\n", twelfthRow, 
    "\n alcoholPercentage :\n", alcoholPercentage, 
    "\n alcoholAverage :\n", alcoholAverage
)



minPh = np.min(data[:, 8:9])
maxPh = np.max(data[:, 8:9])
ph25Th = np.percentile(data[:, 8:9], 25)
ph50Th = np.percentile(data[:, 8:9], 50)
ph75Th = np.percentile(data[:, 8:9], 75)


print(
    "minPH :\n", minPh, 
    "\n maxPh :\n", maxPh, 
    "\n ph25Th :\n", ph25Th, 
    "\n ph50Th :\n", ph50Th, 
    "\n ph75Th \n", ph75Th
)



sulphateColumn = data[:, 9]
qualityColumn = data[:, 11]

sulphatePercentage = np.percentile(sulphateColumn, 20)
is20PercentMask = sulphateColumn < sulphatePercentage

percent20Quality = qualityColumn[is20PercentMask]
qualityAverage = np.mean(percent20Quality)

print(is20PercentMask)
print(qualityAverage)


maxQuality = np.max(qualityColumn)




bestQualityMask = qualityColumn == maxQuality

meanBestQuality = np.mean(data[bestQualityMask], axis=0)
print("Best of the Best :\n", meanBestQuality)



arraySizeInBytes :
 76752 
 secondRow :
 [[ 7.8     0.88    0.      2.6     0.098  25.     67.      0.9968  3.2
   0.68    9.8     5.    ]] 
 seventhRow :
 [[ 7.9     0.6     0.06    1.6     0.069  15.     59.      0.9964  3.3
   0.46    9.4     5.    ]] 
 twelfthRow :
 [[7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]] 
 alcoholPercentage :
 False 
 alcoholAverage :
 10.422984091619762
minPH :
 2.74 
 maxPh :
 4.01 
 ph25Th :
 3.2100000381469727 
 ph50Th :
 3.309999942779541 
 ph75Th 
 3.4000000953674316
[False False False ... False False False]
5.1854305
Best of the Best :
 [ 8.566666    0.4233333   0.39111114  2.5777776   0.06844445 13.277778
 33.444443    0.99521226  3.2672222   0.76777774 12.094444    8.        ]


In [101]:
import numpy as np
from itertools import combinations
from functools import reduce
matrix = np.genfromtxt("model_forecasts.txt", delimiter=",", dtype=np.float32)
matrix = np.abs(matrix)
matrix


all_matches = list(combinations([0,1,2,3,4,5,6,7,8,9], 2))

def is_valid_match_set(match_set):
    flat_matches = reduce(lambda x, y: x + y, match_set, ())
    return len(set(flat_matches)) == len(flat_matches)

def find_all_valid_matches(matches, n):
    if n == 0:
        return [[]]
    if not matches:
        return []
    
    match, rest = matches[0], matches[1:]
    with_match = list(filter(lambda x: is_valid_match_set([match] + x), find_all_valid_matches(rest, n-1)))
    without_match = find_all_valid_matches(rest, n)
    
    return list(map(lambda x: [match] + x, with_match)) + without_match

all_valid_matches = list(filter(lambda x: len(x) == 5, find_all_valid_matches(all_matches, 5)))


def unpack_pairs(row_idx, col_idx):
    return matrix[row_idx][col_idx]

def rows(arr):
    rows = arr[:,0]
    cols = arr[:,1]
    
    unpack = np.vectorize(unpack_pairs)
    result = unpack(rows.astype(int), cols.astype(int))
    mean = np.mean(result)
    return mean

def tab(arr, i, result):    
    if i == len(arr):
        return result

    result.append(rows(arr[i]))
    i = i + 1
    return tab(arr, i, result)


test = tab(np.array(all_valid_matches), 0, [])
array = np.array(all_valid_matches[np.argmin(test)])
formatted_array = np.array([array[:, 0], array[:, 1]])

output = np.vstack([np.char.add("m1_t", formatted_array[0].astype(str)),
                    np.char.add("m1_t", formatted_array[1].astype(str))])

output

array([['m1_t0', 'm1_t1', 'm1_t2', 'm1_t3', 'm1_t5'],
       ['m1_t8', 'm1_t7', 'm1_t9', 'm1_t4', 'm1_t6']], dtype='<U25')